spring:
  application:
    name: sesacrun-back

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver



  # ????? ???? ?? ?? ? ?? ??
  sql:
    init:
      mode: always



  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    defer-datasource-initialization: true

portone:
  apiKey: 0437155210084248
  apiSecret: N8G54DGajiWkAsTnhUOunYX2fs0INiK06OAWg1PTrnLS0RicO4Yaih8d9RWdZqL7rnFx7LdK0QtBuViK